# Frontend Services
# Web UI for Friend-Lite

services:
  webui:
    build:
      context: ../webui
      dockerfile: Dockerfile
      args:
        - VITE_BASE_PATH=${VITE_BASE_PATH:-/}
        - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:8000}
    env_file:
      - ../../../.env.default  # Committed defaults
      - ../.env                # Generated overrides (if exists)
    ports:
      - "${WEBUI_PORT:-3000}:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - chronicle-network

networks:
  chronicle-network:
    name: chronicle-network
    external: true
